# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: bmanu/silverstripe-web-node:7.1-platform
        environment:
          - SS_DATABASE_CLASS=MySQLPDODatabase
          - SS_DATABASE_SERVER=127.0.0.1
          - SS_DATABASE_USERNAME=root
          - SS_DATABASE_PASSWORD=ubuntu
          - SS_DATABASE_NAME=circle_test
          - SS_ENVIRONMENT_TYPE=dev
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_DATABASE=circle_test
          - MYSQL_HOST=127.0.0.1

    working_directory: /var/www/html

    steps:
      - run: /etc/init.d/apache2 start
      - run:
          command: |
            apt-get update
            apt-get install -y xvfb

      - run:
          command: Xvfb :99 -screen 0 1280x1024x24
          background: true

      # Install Java + other dependencies
      - run:
          command: |
            echo 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main' | tee /etc/apt/sources.list.d/webupd8team-java.list
            echo 'deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main' | tee -a /etc/apt/sources.list.d/webupd8team-java.list
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
            apt-get update
            echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
            echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
            apt-get install -y unzip oracle-java9-installer xvfb libxi6 libgconf-2-4 wget libgtk-3-0 libxss1 fonts-liberation libappindicator1 lsb-release xdg-utils

      # Install chrome
      - run:
          command: |
            wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P ~/
            dpkg -i --force-depends ~/google-chrome-stable_current_amd64.deb
            apt-get -fy install

      - checkout

      # Composer Cache + Installation
      - restore_cache:
          keys:
            - v1-composer-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-composer-
      - run: composer install -n --prefer-dist
      # Save all dependancies to cache
      - save_cache:
          key: v1-composer-{{ checksum "composer.lock" }}
          paths:
            - vendor
            - resources

      # NPM Cache + Installation
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
            - v1-npm-deps-

      - run: yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-deps-{{ checksum "package.json" }}

      - run: mv .circleci/.env.circleci .env
      - run: mkdir /var/www/html/assets
      - run: chown -R www-data:www-data /var/www/html
      - run: vendor/bin/sake dev/build flush=1

      # PHP Tests
      - run: vendor/bin/phpunit --verbose

      # JS Linting
      - run: yarn lint

      # JS E2E tests
      - run: yarn nightwatch -- --url http://localhost/

      - store_artifacts:
          path: mysite/tests/nightwatch_screenshots
          destination: nightwatch_screenshots
